export const lightTheme = {
  body: '#ffffff',
  text: '#333333',
  heroBackground: '#e0e0e0',
  cardBackground: '#f1f1f1',
  cardBorder: '#61dafb',
  cardHoverBackground: '#f6ffff',
  aboutBackground: '#f4f4f4',
  aboutText: '#333',
  projectSectionBackground: '#ffffff',
  projectCardBackground: '#f1f1f1',
  projectCardHoverBackground: '#f6ffff',
  projectCardBorder: '#61dafb',
  projectTitle: '#333333',
  projectDescription: '#666666',
  contactBackground: '#282c34',
  contactText: '#ffffff',
  contactSectionBackground: '#282c34',
  contactLinksColor: '#333333',
  footerBackground: '#282c34',
  footerTextColor: '#ffffff'
};

export const darkTheme = {
  body: '#1e1e1e',
  text: '#f4f4f4',
  heroBackground: '#2c2c2c',
  cardBackground: '#2c2c2c',
  cardBorder: '#61dafb',
  cardHoverBackground: '#333',
  aboutBackground: '#2c2c2c',
  aboutText: '#e0e0e0',
  projectSectionBackground: '#2e2e2e',
  projectCardBackground: '#2c2c2c',
  projectCardHoverBackground: '#333',
  projectCardBorder: '#61dafb',
  projectTitle: '#ffffff',
  projectDescription: '#cccccc',
  contactBackground: '#282c34',
  contactText: '#ffffff',
  contactSectionBackground: '#333333',
  contactLinksColor: '#ffffff',
  footerBackground: '#444444',
  footerTextColor: '#ffffff'
};